title: Blog
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Testing 

# social links
twitter_username: ohaga
github_username:  ohaga

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
